// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

#include <stdio.h>

char findTheDifference(char* s, char* t) {
    int sum_s = 0;
    int sum_t = 0;
    for (int i = 0; s[i] != '\0'; i++) {
        sum_s = sum_s + s[i];
    }
    for (int i = 0; t[i] != '\0'; i++) {
        sum_t = sum_t + t[i];
    }
    return (sum_t - sum_s);
}

int main (){
    char * word1 = "abc";
    char * word2 = "akbc";
    char result = findTheDifference(word1, word2);

    printf("%c\n", result);
      

}